name : Build source distribution, wheels, test and publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_BUILD_VERBOSITY: 2

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {package}/tests/unit

      - name: Display wheels
        run: ls -R
        working-directory: dist

      - name: Store wheel as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build source tarball
        run: python setup.py sdist

      - name: Store sdist as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist



